[package]
name = "compio-net"
version = "0.1.0"
description = "Networking IO for compio"
categories = ["asynchronous", "network-programming"]
keywords = ["async", "net"]
edition = { workspace = true }
authors = { workspace = true }
readme = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg docsrs"]

[dependencies]
# Workspace dependencies
compio-buf = { workspace = true }
compio-driver = { workspace = true }
compio-io = { workspace = true, optional = true }
compio-runtime = { workspace = true, optional = true }
compio-util = { workspace = true }

socket2 = { version = "0.5", features = ["all"] }

# Shared dev dependencies for all platforms
[dev-dependencies]
futures-util = "0.3"
tempfile = "3"

[features]
runtime = ["dep:compio-io", "dep:compio-runtime"]
